# 
# ░██████╗██╗░░░██╗███╗░░██╗░██████╗██╗░░██╗██╗░░░██╗██╗░░░░░██╗░░██╗███████╗██████╗░░██████╗
# ██╔════╝██║░░░██║████╗░██║██╔════╝██║░░██║██║░░░██║██║░░░░░██║░██╔╝██╔════╝██╔══██╗██╔════╝
# ╚█████╗░██║░░░██║██╔██╗██║╚█████╗░███████║██║░░░██║██║░░░░░█████═╝░█████╗░░██████╔╝╚█████╗░
# ░╚═══██╗██║░░░██║██║╚████║░╚═══██╗██╔══██║██║░░░██║██║░░░░░██╔═██╗░██╔══╝░░██╔══██╗░╚═══██╗
# ██████╔╝╚██████╔╝██║░╚███║██████╔╝██║░░██║╚██████╔╝███████╗██║░╚██╗███████╗██║░░██║██████╔╝
# ╚═════╝░░╚═════╝░╚═╝░░╚══╝╚═════╝░╚═╝░░╚═╝░╚═════╝░╚══════╝╚═╝░░╚═╝╚══════╝╚═╝░░╚═╝╚═════╝░

# ᴡᴇʙsɪᴛᴇ - https://studio.sunworld.pro , ᴀᴜᴛʜᴏʀ - sᴜɴsᴛᴜᴅɪᴏ
# Нашли баг, Есть вопросы? Пишите в Discord: https://studio.sunworld.pro/discord

# ================================================================================================
#                                        ПРАВА ДОСТУПА
# ================================================================================================
# sunshulkers.use - Разрешает игроку использовать открытие шалкеров из инвентаря
# sunshulkers.admin - Разрешает доступ к административным командам  
# sunshulkers.bypass - Игнорирует ограничения кулдауна и список запрещенных предметов
# sunshulkers.color - Разрешает использование цветов в именах шалкеров через наковальню
# sunshulkers.rename - Разрешает переименование шалкеров через специальную кнопку в наковальне
# sunshulkers.autocollect - Разрешает автоматический сбор предметов в шалкер в руке

# ================================================================================================
#                                      СООБЩЕНИЯ И ПРЕФИКС  
# ================================================================================================
# Поддерживает MiniMessage, HEX цвета (&#FFFFFF) и & коды. Оставьте пустым для отключения.
messages:
  prefix: "<gradient:#9863E7:#4498DB>SunShulkers</gradient> &7-" # Префикс плагина
  
  reload-config: "Конфигурация плагина перезагружена." # Сообщение о перезагрузке
  no-permission: "У вас недостаточно прав." # Сообщение при недостатке прав
  
  cooldown: "Подождите {time}с. перед открытием шалкера." # {time} - время кулдауна
  blacklisted-item: "Этот предмет нельзя помещать в шалкер!" # Запрещенный предмет
  blacklisted-world: "В мире {world_name} нельзя открывать шалкеры!" # {world_name} - название мира
  item-deleted: "Запрещенный предмет удален!" # Сообщение при удалении запрещенного предмета
  
  open-message: "Вы открыли шалкер!" # Сообщение при открытии
  close-message: "Вы закрыли шалкер!" # Сообщение при закрытии
  
  autocollect-enabled: "Автосбор предметов в шалкер включен!" # Сообщение при включении автосбора
  autocollect-disabled: "Автосбор предметов в шалкер отключен!" # Сообщение при отключении автосбора
  autocollect-no-space: "В шалкере нет места для предмета!" # Сообщение когда в шалкере нет места
  
  # Сообщения для переименования через наковальню
  rename-prompt: "Введите новое имя для шалкера в чат. {supported-formats}"
  rename-supported-formats: "Поддерживаются цвета: &a, &c, &f (legacy коды), &#FF0000 (HEX), (MiniMessage)"
  rename-success: "Шалкер переименован в: {name}" # {name} - новое имя
  rename-cancelled: "Переименование отменено."
  rename-timeout: "Время ожидания истекло. Переименование отменено."
  close-on-attack: "Шалкер закрыт при атаке!" # Сообщение при закрытии GUI по атаке

# ================================================================================================
#                                        ЗВУКИ
# ================================================================================================
sounds:
  open: "BLOCK_SHULKER_BOX_OPEN" # Звук при открытии шалкера
  close: "BLOCK_SHULKER_BOX_CLOSE" # Звук при закрытии шалкера
  pickup: "ENTITY_ITEM_PICKUP" # Звук при автоматическом сборе предметов

# ================================================================================================
#                                    ОСНОВНЫЕ НАСТРОЙКИ
# ================================================================================================
settings:
  # Формат отображения имени шалкера в GUI. {shulker_name} заменяется на название шалкера
  shulker-name-format: "{shulker_name}"
  
  # Задержка открытия шалкера из инвентаря в секундах
  cooldown: 5
  
  # Показывать ли визуальный кулдаун на шалкерах (серая полоска как у жемчуга края)
  visual-cooldown: true
  
  # Предметы, которые нельзя класть в шалкер
  blacklisted-items:
  - bedrock
  - barrier
  
  # Удалять ли запрещенные предметы вместо блокировки
  delete-blacklisted-items: false
  
  # Миры, в которых нельзя открывать шалкер из инвентаря
  blacklisted-worlds:
  - world_event
  
  # "Умное" открытие - если игрок НЕ смотрит на блок, открывается через плагин
  # Если смотрит на блок - размещается как обычно
  smart-placement: true
  
  # Автоматический сбор предметов в шалкер, который держит в руке игрок
  auto-collect:
    enabled: true # Включить ли функцию автосбора
    permission: "sunshulkers.autocollect" # Право для использования автосбора
    notify-no-space: true # Уведомлять ли игрока когда в шалкере нет места
    default-enabled: true # Включен ли автосбор по умолчанию для игроков с правом (sunshulkers.autocollect)
  # Закрывать интерфейс при атаке игрока
  close-on-attack: false # true/false
  
  # Настройки базы данных H2 (необязательно)
  database:
    # Режим совместимости (MySQL, PostgreSQL, Oracle, MSSQLServer)
    compatibility-mode: "MySQL"
    # Имя файла базы данных (без расширения)
    filename: "data"
    # Пользователь базы данных
    username: "sa"
    # Пароль базы данных (пустой по умолчанию)
    password: ""

# ================================================================================================
#                                    РЕЖИМЫ ОТКРЫТИЯ
# ================================================================================================
open-modes:
  # Режимы для открытия шалкера В РУКЕ (вне инвентаря)
  # Доступные: RIGHT_CLICK, SHIFT_RIGHT_CLICK, LEFT_CLICK, SHIFT_LEFT_CLICK, ANY_CLICK, SHIFT_ANY_CLICK
  # МОЖНО УКАЗАТЬ НЕСКОЛЬКО РЕЖИМОВ:
  hand-modes:
  - SHIFT_RIGHT_CLICK
  # - RIGHT_CLICK      # Раскомментируйте для добавления обычного ПКМ
  # - LEFT_CLICK       # Раскомментируйте для добавления ЛКМ
  # - ANY_CLICK        # Раскомментируйте для любого клика
  
  # Режимы для открытия шалкера ИЗ ИНВЕНТАРЯ
  inventory-modes: 
  - SHIFT_RIGHT_CLICK
  # - RIGHT_CLICK      # Раскомментируйте для добавления обычного ПКМ
  # - LEFT_CLICK       # Раскомментируйте для добавления ЛКМ
  # - ANY_CLICK        # Раскомментируйте для любого клика

# ================================================================================================
#                                  НАСТРОЙКИ НАКОВАЛЬНИ
# ================================================================================================
anvil:
  # Включить ли систему переименования через наковальню
  enabled: true
  
  # Право для использования обычного переименования (без цветов)
  rename-permission: "sunshulkers.rename"
  
  # Право для использования цветов в именах шалкеров
  color-permission: "sunshulkers.color"
  
  # Настройки кнопки переименования (появляется во втором слоте наковальни)
  rename-button:
    material: "NAME_TAG" # Материал кнопки
    name: "&e&lПереименовать шалкер" # Имя кнопки
    lore: # Описание кнопки
    - "&7Нажмите чтобы переименовать"
    - "&7шалкер с поддержкой цветов!"
    - ""
    - "&aЛКМ &7- переименовать"
    - "&cПКМ &7- отменить"
    enchanted: true # Сделать ли кнопку зачарованной (свечение)
    
  # Максимальное время ожидания ввода имени (в секундах)
  input-timeout: 30
